/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author dikshadesai
 */
public class AssignToDeliverymanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignToDeliverymanJPanel
     */
    JPanel userProcessContainer;
    Order order;
    UserAccount userAccount;
    Restaurant restaurant;
    DeliveryManDirectory deliveryManDirectory;
    public AssignToDeliverymanJPanel(JPanel userProcessContainer, Order order, DeliveryManDirectory deliveryManDirectory, Restaurant restaurant, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        this.deliveryManDirectory = deliveryManDirectory;
        this.restaurant = restaurant;
        this.userAccount = userAccount;
        dpdDeliveryman.removeAllItems();
        this.populateDeliveryMan();
        orderIdTextField.setEditable(false);
        orderIdTextField.setText(Integer.toString(this.order.getOrderId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populateDeliveryMan()
    {
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            dpdDeliveryman.addItem(d.getName());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        dpdDeliveryman = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();

        jLabel4.setText("Select DeliveryMan:");

        dpdDeliveryman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dpdDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdDeliverymanActionPerformed(evt);
            }
        });

        jLabel1.setText("Order id:");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssign)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(dpdDeliveryman, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dpdDeliveryman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAssign)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dpdDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdDeliverymanActionPerformed
        
    }//GEN-LAST:event_dpdDeliverymanActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your h)andling code here:
        DeliveryMan dm = null;
        String d1 = (String)dpdDeliveryman.getSelectedItem();
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            if(d.getName().equals(d1))
            {
                dm = d;
            }
        }
        for (WorkRequest w : this.restaurant.getWorkQueue().getWorkRequestList()) 
            {
                if((w.getOrder() != null) && (w.getOrder().getOrderId() == order.getOrderId()))
                {
                   w.setSender(this.userAccount);
                   w.setStatus("Assinged to delivery Man");
                   dm.getWorkQueue().getWorkRequestList().add(w);
                   System.out.println("d work " + dm.getWorkQueue().getWorkRequestList());
                   break;
                }
  
            }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox<String> dpdDeliveryman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField orderIdTextField;
    // End of variables declaration//GEN-END:variables
}
